version: '3.7'

services:
  db:
    image: mariadb:latest
    volumes:
      - .\db\:/var/lib/mysql
      - .\db\init\:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    # expose:
    #  - 3306
    env_file: .\db\.env

  backend:
    image: python:3.7-bullseye
    ports:
      - 8080:8080
    # expose:
    #   - 8080
    volumes:
      - .\backend\:/home/
    working_dir: /home
    command: bash -c "apt-get update && apt-get install vim -y && pip install --upgrade pip && pip install fastapi && pip install uvicorn && pip install pandas && pip install numpy && pip install psycopg2-binary && pip install pymysql && pip install sqlalchemy && pip install openpyxl && python db_init.py && python main.py && tail -f /dev/null"
    depends_on:
      - db
  
  frontend:
    image: node:current-bullseye

    ports:
      - 3000:3000
    # expose:
    #   - 3000
    volumes:
      - .\frontend\:/home/
    working_dir: /home
    depends_on:
      - backend
    command: bash -c "apt-get update && apt-get install vim -y && npm install && npm start && tail -f /dev/null"

  webserver:
    image: nginx:stable
    ports:
    - 80:80
    volumes: 
    - .\nginx\default.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
